<?php

namespace Omnipay\Ipay88\Message;

use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Ipay88\Traits\PaymentResponseTrait;

class RequeryPaymentResponse extends AbstractResponse
{
    use PaymentResponseTrait;

    /**
     * Is the response successful?
     *
     * @return boolean
     */
    public function isSuccessful(): bool
    {
        return (string)($this->data['Status'] ?? '') === '1';
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return null|string
     */
    public function getTransactionId(): ?string
    {
        return $this->data['RefNo'] ?? null;
    }

    /**
     * Gateway Reference
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference(): ?string
    {
        return $this->data['TransId'] ?? null;
    }
}