<?php

namespace Omnipay\Ipay88\Message;

use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Ipay88\Traits\PaymentResponseTrait;

class RequeryPaymentResponse extends AbstractResponse
{
    use PaymentResponseTrait;

    /**
     * Is the response successful?
     *
     * @return boolean
     */
    public function isSuccessful(): bool
    {
        $status = empty($this->data['Status']) ? '' : $this->data['Status'];

        return (string)$status === '1';
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return null|string
     */
    public function getTransactionId(): ?string
    {
        return empty($this->data['RefNo']) ? null : $this->data['RefNo'];
    }

    /**
     * Gateway Reference
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference(): ?string
    {
        return empty($this->data['TransId']) ? null : $this->data['TransId'];
    }
}